version: '3.8'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - ARANGO_URL=http://arangodb:8529
      - ARANGO_USERNAME=root
      - ARANGO_PASSWORD=${ARANGO_ROOT_PASSWORD}
      - ARANGO_DB_NAME=watson_stark
    depends_on:
      - arangodb
    networks:
      - app-network

  arangodb:
    image: arangodb:3.11
    environment:
      - ARANGO_ROOT_PASSWORD=${ARANGO_ROOT_PASSWORD}
    ports:
      - "8529:8529"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge